[program:raddflix_wa_bot]
directory=/opt/radd-hub/bots/whatsapp
command=/usr/bin/node /opt/radd-hub/bots/whatsapp/index.js
autostart=true
autorestart=true
startretries=5
startsecs=10
stopwaitsecs=30
redirect_stderr=true
stdout_logfile=/var/log/supervisor/raddflix_wa_bot.log
stdout_logfile_maxbytes=5MB
stdout_logfile_backups=3
environment=NODE_ENV="production"
user=ubuntu
